Revert unit test changes.
This reverts commits 9173f03f1e724e6b338ce5b366d7d25d2397950b,
f7ac65bcf3ba2f878171ffb3e9b1b90df01e7af0 and
e807cb80e8d98ded2516c1644aa39d7111d169b2.

These caused by build to fail as follows:
  $ python setup.py build
  running build
  running build_py
  copying tkp/tests/decorators.py -> ../build/tkp/python-packages/lib.linux-x86_64-2.6/tkp/tests
  copying tkp/tests/db_subs.py -> ../build/tkp/python-packages/lib.linux-x86_64-2.6/tkp/tests
  error: package directory 'tkp/tests/utility' does not exist