Fix for upgrade script 10_to_11
As Tim experienced the error
monetdb.exceptions.OperationalError: 40002!ALTER TABLE: NOT NULL constraint violated for column image.delta
occurred.

A temporary column name is introduced in the script to circumvent this.